### ISSUE TITLE
Users table columns need allow null

### ISSUE THREAD

**Issue by kevingelion** [kronusme/dota2-api#101]
After looking more closely at #100 I realized that it was due to an issue inserting new users into the database when saving. When saving new accounts, only the `account_id` and `steamid` are attempted to be inserted. However, I was getting an error that `personaname`, `avatar`, and `profileurl` need default values.

I fixed this by allowing `NULL` on these 3 columns. Is there a better way of handling this?

**Comment by kronusme** [comment]
Hi, @kevingelion. You are right - this columns should allow `null`.
