### ISSUE TITLE
Вопрос по поводу получении информации

### ISSUE THREAD

**Issue by oleghalin** [kronusme/dota2-api#102]
Здравствуй. Заинтересовался данным творением, стало интересно как все это работает, все понял, запросы все понятны кроме одного. Каким способом Вы записываете данные о игре в БД в тот момент когда она еще идет (каким запросом получаете их), перебираете ответ из LiveLeagues? (очень интересуют таблицы)

**Comment by kevingelion** [comment]
GitHub issues shouldn't be used as a getting started tool.

**Comment by oleghalin** [comment]
This question about this tool, im intersting what request he using cause i cant understand how he update form him code
