### ISSUE TITLE
Return Wrong Users ID

### ISSUE THREAD

**Issue by pink-anna** [kronusme/dota2-api#108]
hey , when i try to get players id i see wrong values
 i use this codes
`
use Dota2Api\Api;
Api::init('******************',***********);

$mm = new Dota2Api\Mappers\MatchMapperWeb(2375742867);
$match = $mm->load();
$slots = $match->getAllSlots();
foreach($slots as $slot) {
    echo $slot->get('account_id') . '<br/>';
}`

player id 0 1 2 3 4 slots and 128 131 132 slots are same
just return true id of 0 129 130 players

**Comment by kronusme** [comment]
@pink-anna, it's a public game, so only two players were not Anonimous. It's ok. Anonimous players always have id `4294967295`.
