### ISSUE TITLE
Fix MatchesMapperDb

### ISSUE THREAD

**Issue by et1a1nen** [kronusme/dota2-api#109]
Hello!
Please, change in
 includes/Mappers/MatchesMapperDb.php:346
heroid for hero_id

Another thing is:
with setAccountId and\or setHeroId set, and if no matches found, MatchesMapperDb will return all matches.
Can you fix it?
Probably something like in:
 includes/Mappers/MatchesMapperDb.php:309
`else { `
`return array();`
`}`

**Comment by kronusme** [comment]
Hi, @et1a1nen. Thanks for report and sorry for long response-time.
> heroid for hero_id
Fixed
>with setAccountId and\or setHeroId set, and if no matches found, MatchesMapperDb will return all matches.
It's normal behavior. You may create your own class and override method `_getMatchesIdsFromMatches`
