### ISSUE TITLE
README-Example triggers Catchable Fatal Error

### ISSUE THREAD

**Issue by grasdaggel** [kronusme/dota2-api#110]
```
$matchesMapperWeb = new Dota2Api\Mappers\MatchesMapperWeb();
$matchesShortInfo = $matchesMapperWeb->load();
foreach ($matchesShortInfo as $key=>$matchShortInfo) {
    $matchMapper = new Dota2Api\Mappers\MatchMapperWeb($key);
    $match = $matchMapper->load();
    $mm = new Dota2Api\Mappers\MatchMapperDb();
    $mm->save($match);

```

triggers

>  Catchable fatal error: Argument 1 passed to Dota2Api\Mappers\MatchMapperDb::save() must be an instance of Dota2Api\Models\Match, null given, called in /dota2/index22.php on line 18 and defined in /dota2/includes/Mappers/MatchMapperDb.php on line 104

Its the example of line 104 without the player info in it. :)

**Comment by kronusme** [comment]
Hi, @grasdaggel. I guess problem exists with API. It's pretty often return no-data for `GetMatchDetails`. I'll update example to check `null`-values.

**Comment by grasdaggel** [comment]
Thanks kronusme. In the meantime I tried to setup my own API connector from scratch, and I went fine by checking if the JSON is either an array (is_array) and !empty. This way, I was able to sort them out.
