### ISSUE TITLE
what is 'table_prefix_' ? 

### ISSUE THREAD

**Issue by milobluebell** [kronusme/dota2-api#116]
what does the 'table_prefix_'  mean?   table name?

**Comment by kronusme** [comment]
`ddd_users`, `ddd_matches`
`ddd_` - table prefix
It may be used if your DB already have tables used by `dota2-api` (e.g., `users`, `matches` etc). In this case, you should manually update table names in the `db_latest.sql` and execute it.
If you are using standalone database for dota2-api ``table_prefix` is not needed for you.

**Comment by milobluebell** [comment]
thanks a lot !
