### ISSUE TITLE
Как получить список предметов?

### ISSUE THREAD

**Issue by Dota2Vus** [kronusme/dota2-api#71]
Здравствуйте.Я бы хотел сделать такую функцию после авторизации на сайте через STEAM пользователь мог получить список предметов инвентаря.Далее он мог выбрать предмет из всех предметов.Типо как http://live-dota.ru/market/   http://www.dota2lounge.com/  и тд.Как это реализовать?Помогите пожалуйста.При необходимости заплачу

**Comment by yesworld** [comment]
Можно получить инвентарь таким образом:
```php
$id_game = 570; //Id игры.
$nick_name = 'Dota2Vus';
$url = file_get_contents( "http://steamcommunity.com/id/$nick_name/inventory/json/$id_game/2");
```
Вот полный список $id игр: http://api.steampowered.com/ISteamApps/GetAppList/v2
