### ISSUE TITLE
Еще вопрос

### ISSUE THREAD

**Issue by fellixZZZ** [kronusme/dota2-api#77]
Привет еще раз. Можешь подсказать, как сделать так, чтобы при получении матчей лиги в лайве (используя league_mapper) взять оттуда match_id и сразу сохранить его в бд? Больше всего интересует, как взять id.

**Comment by kronusme** [comment]
Привет. match_id появляется после того как матч уже сыгран (то есть, физически матч сохранился в БД у Valve).

**Comment by fellixZZZ** [comment]
Ясно, спасибо.
