### ISSUE TITLE
Regions.json does does not account for South Africa Server

### ISSUE THREAD

**Issue by Brian-McG** [kronusme/dota2-api#80]
The South Africa server registers as South America from your Regions.json file.

I don't know what the ID of the South Africa server is though.

**Comment by Dota2Vus** [comment]
Как записать в бд все предметы dota2 + инфо о редкости качестве и тд

**Comment by dongchuant** [comment]
is the matchId definitely an INT32?

thanks

**Comment by sinneduy** [comment]
@Brian-McG seems like you might want to PR https://github.com/Brian-McG/dota2-api/commit/9f1a3b25024360d8afae7eb8d0e6afc382cd6337 into this repo?
