### ISSUE TITLE
is the matchId definitely an INT32

### ISSUE THREAD

**Issue by dongchuant** [kronusme/dota2-api#81]
is the matchId definitely an INT32?
is there a 32-bit matchId and a 64-bit matchId  both?
64-bit matchId = 32-bit matchId + 76561197960265728 ?

thanks!

**Comment by kronusme** [comment]
Hello. I didn't hear about 64-bit matchid.
Maybe someone can answer more (check on [dev.dota2.com](http://dev.dota2.com/))

**Comment by dongchuant** [comment]
Hello. In your code, matchId is regarded as int.
However, matchId is an unsigned int . What if matchId is greater than 2^31-1?

Line 24 in MatchMapper.php:
$this->_match_id = (int)$matchId;

**Comment by kronusme** [comment]
For current moment match_id is about 2^30, so i have some time to think about this.
