### ISSUE TITLE
64-bit account ids

### ISSUE THREAD

**Issue by lukthy** [kronusme/dota2-api#87]
Currently, the account id passed to MatchesMapper's setAccountId() method gets casted to a 32-bit int, and ids are 64-bit ints. I believe php doesn't support long ints natively, so the solution could be to save the id as a string.

**Comment by Sjaakmoes** [comment]
PHP supports 64-bit integers on 64-bit platforms (except for Windows).
Casting the 64-bit SteamID's as string is a good solution to make sure it works on all platforms.
