### ISSUE TITLE
Foreign Key constraint fails when trying to upload matches to database

### ISSUE THREAD

**Issue by olazawhat** [kronusme/dota2-api#95]
using this code:
<code>$matchesMapperWeb = new Dota2Api\Mappers\MatchesMapperWeb();
$matchesMapperWeb->setAccountId(76561198034463184);
$matchesShortInfo = $matchesMapperWeb->load();
foreach ($matchesShortInfo as $key=>$matchShortInfo) {
    $matchMapper = new Dota2Api\Mappers\MatchMapperWeb($key);
    $match = $matchMapper->load();
    $mm = new Dota2Api\Mappers\MatchMapperDb();
    $mm->save($match);
}</code>
I produce this error: 
<code>(`thundercatsdata`.`ability_upgrades`, CONSTRAINT `FK_ability_upgrades_slots` FOREIGN KEY (`slot_id`) REFERENCES `slots` (`id`))SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails </code>
I ran your sql script, and the other database updates I have done so far run fine.

**Comment by kronusme** [comment]
https://github.com/kronusme/dota2-api#important

> Before parsing and saving leagues matches to your DB, make sure that you've saved leagues to the DB (using leaguesMapperWeb! If you try to save some "public" matches, you should REMOVE foreign key for field leagueid in the table matches!
