### ISSUE TITLE
Only Sends Back Anonymous Players Data

### ISSUE THREAD

**Issue by Nageki4Ever** [kronusme/dota2-api#99]
When I try to use the api to gain match information from a particular MatchID, it only gives me the player info of the anonymous/private players and not those of lets say me and my friends. 

Heres the code: 

<?php

require_once 'vendor\autoload.php';

use Dota2Api\Api;

Api::init('*************', array('^^^^^^^^', 'root', 'cheese', 'dota2', ''));

$MatchID =  $_POST["MatchID"];

$mm = new Dota2Api\Mappers\MatchMapperWeb($MatchID);
$match = $mm->load();

$saver = new Dota2Api\Mappers\MatchMapperDb();
$saver->save($match);
echo "success";

?>

The MatchID is obtained from here: 

<head>
	<title>Test Web Api</title>
</head>
<body>

<form action="testdotaapi.php" method="post">
MatchID: <input type="text" name="MatchID"><br>

<input type="submit">
</form>

</body>
</html>

Thanks for the help!

**Comment by kronusme** [comment]
@Nageki4Ever, which `match_id` you tried? Show it to me and I'll check it.

**Comment by Szewski** [comment]
OMG HOW TO UNSUBSCRIBE DAT MESSAGES

22.12.2015, 11:27, "KronuS" <notifications@github.com>:

**Comment by kronusme** [comment]
@Szewski, Try "Unwatch" and "Unsubscribe buttons on this page.

**Comment by Nageki4Ever** [comment]
I tried a variety of match_Ids and none of them seemed to work. I'm not at my PC right now but I used ones similar to this: 

1789520679
1838055725

Thanks! Sorry I couldn't give you the exact ones but it seemed to happen go each one

**Comment by kronusme** [comment]
As I see in the API-request (https://api.steampowered.com/IDOTA2Match_570/GetMatchDetails/v001/?key=****************************&language=en_us&match_id=1789520679), there are 5 anonimous players (2 in the Radiant team and 3 in the Dire team). Checking this match in dotabuff - http://www.dotabuff.com/matches/1789520679. All data is correct.

**Comment by Nageki4Ever** [comment]
thats the problem I have, I don't quite understand why its only giving me anonymous player data and not the data from the players who aren't anonymous
